version: "3.9"
services:
  odoo:
    entrypoint: ./odoo-bin --addons-path="addons,enterprise,addons_demo,netsurf_addons" -r odoo -w mysecretpassword -d odoo --db_host db -u netsurf_product_extension --data-dir /home/odoo_adm/data/
    build: .
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /home/odoo_adm/odoo
      - odoo-volume:/home/odoo_adm/data/
    environment:
      - PGHOST=db
      - PGDATABASE=odoo-vasil
      - PGUSER=odoo
      - PGPASSWORD=mysecretpassword
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=odoo
    # volumes:
    #   - /usr/local/var/postgresql@13
volumes:
  odoo-volume:
